[package]
name = "ufc-ripper"
version = "2.2.0"
description = "Video downloader tool for UFC Fight Pass"
authors = ["Mahesh Bandara Wijerathna <m4heshd@gmail.com>"]
license = "MIT"
repository = "https://github.com/m4heshd/ufc-ripper"
edition = "2021"

[dependencies]
