name: test

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v4
      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Install npm deps
      - name: Install npm dependencies
        run: npm install --no-audit
      # Build Vue frontend
      - name: Build frontend
        run: npm run build
      # Set up Rust and Cargo
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.81.0
      # Run tests
      - name: Run tests
        run: cargo test-backend
